import type { Slider } from '../builders.js';
import { numberSlider } from '../builders.js';

export const AI_SLIDERS: readonly Slider[] = [
  numberSlider(
    'ai.automatableShareStart',
    'Initial automatable share',
    'ai',
    'share',
    0.1,
    0,
    0.5,
    'Share of tasks software can already do in month zero. Adoption follows an S-curve from this share up to the final automatable share. The final share has to be at least this large. If the two shares are equal, the curve stays put, firms do not adopt AI, and production, hiring, and ownership stay on the path with no AI effect.',
  ),
  numberSlider(
    'ai.automatableShareEnd',
    'Final automatable share',
    'ai',
    'share',
    0.9,
    0.3,
    1,
    'Share of tasks software can do once the adoption curve has finished. Only the rise from the starting share can be adopted, and only the non-physical part of that rise adds capacity. While adoption is underway and capacity has actually increased, a household whose skill is below the current automatable share may apply to only one firm a month.',
  ),
  numberSlider(
    'ai.adoptionMidpointYear',
    'AI adoption midpoint',
    'ai',
    'years',
    10,
    1,
    40,
    'Year when the automatable share is halfway from the start share to the end share. An earlier year brings the S-curve forward. The curve is flat, and this year does nothing, when the start and end shares are equal.',
  ),
  numberSlider(
    'ai.adoptionSteepness',
    'AI adoption steepness',
    'ai',
    '1/year',
    0.15,
    0.1,
    1.5,
    'How sharply the automatable share climbs through its S-curve, per year. A higher value bunches the change around the midpoint year. A lower value spreads the same change over more years. It has no effect when the start and end shares are equal.',
  ),
  numberSlider(
    'ai.computeCostDeclineRate',
    'Compute cost decline',
    'ai',
    '1/year',
    0.3,
    0,
    0.6,
    'Annual rate at which AI compute gets cheaper. Cost starts equal to the wage and is multiplied by one minus this rate each year. Firms take up newly automatable tasks only once that cost is below the wage. Any positive rate makes cost fall below the wage after the first year. At zero, cost stays at the wage and this channel adds no capacity.',
  ),
  numberSlider(
    'ai.physicalTaskShare',
    'Reachable share',
    'ai',
    'share',
    0.7,
    0,
    0.7,
    'Blocked share of an automatable-share rise before robotics. The control shows one minus this stored value, the reachable share. The default stored value 0.70 reads as 0.30, so 30 percent of the rise counts before robotics. Robotics raises the reachable share to one. A higher stored value blocks more of the rise. If the automatable share has risen by 0.2 and this stored value is 0.3, about 14 percent of tasks are adopted while the block is intact. At 0 the whole rise counts. Displacement, which limits job search, begins only once capacity has actually increased.',
  ),
  numberSlider(
    'ai.bullishness',
    'AI bullishness',
    'ai',
    'index',
    0,
    0,
    2,
    'How large the productivity gain is on each adopted task. At 0, the default, the gain is one tenth of the unit reference — about the scale of a decade of internet-era productivity gains once the adoption curve finishes — and unemployment barely moves. At 1 each adopted task adds its full share to capacity and the gain saturates with the S-curve. Above 1 the same level formula compounds: each point above 1 adds 15 percent a year of growth to the task gain with no ceiling, so at 2 the gain grows at 15 percent a year. Hiring still follows the adopted task share, capped by the physical-task share until robots open it. Equal start and end automatable shares still turn the whole AI channel off. The anchors are a modeling guess after Korinek et al. 2026 and the internet-era productivity literature.',
  ),
  numberSlider(
    'ai.roboticsStartYear',
    'Robotics start',
    'ai',
    'years',
    20,
    0,
    50,
    'Year from the start of the run when mass robotics begins to open physical tasks. The core does not read the calendar. Tick 0 is month 0, and charts label that month as the month the page is opened, so the default of 20 is about 2046 when month 0 is read as late 2026. Until this year the reachable share stays at the control value. A start year at or past the last year of the run leaves the block intact for that run.',
  ),
  numberSlider(
    'ai.roboticsRampYears',
    'Robotics ramp',
    'ai',
    'years',
    16,
    1,
    30,
    'How many years the reachable share takes to rise from the control value to one after the robotics start year. The path is a straight line. At the defaults the block is intact through year 20, half gone around year 28, and gone by year 36. A finished ramp lets the automatable share that software already reached cover the old physical tasks as well. Tasks outside the final automatable share stay human.',
  ),
  numberSlider(
    'ai.ownershipConcentration',
    'AI ownership concentration',
    'aiClaims',
    'share',
    0.8,
    0.1,
    0.99,
    'How strongly profits skew toward high-skill households as the AI factor rises. Profit shares normally follow skill raised to 1.5. Once AI capacity is above normal, that exponent rises by this value times the extra capacity factor, so the same skill gaps claim a larger share of profits. It does not choose which households own agents.',
  ),
  numberSlider(
    'ai.ownerShareCeiling',
    'Owner-share ceiling',
    'aiClaims',
    'share',
    0.95,
    0,
    1,
    'Highest fraction of households that own an agent. The owner share rises along the adoption curve from zero to this ceiling. Households become owners in id order, lowest first. At 0.95 with 1,000 households, 950 households can own an agent once the curve has finished. At zero, no agents are created. The curve stays at zero when the start and end automatable shares are equal.',
  ),
  numberSlider(
    'ai.agentsPerOwnerCeiling',
    'Agents per owner',
    'aiClaims',
    'agents',
    20,
    0,
    50,
    'How many agents one owner holds once the adoption curve has finished. The count rises along that curve from zero to this ceiling. New agents go to owners who are short of the current level. An existing agent keeps its owner and its deposit. At zero, no agents are created.',
  ),
  numberSlider(
    'ai.computeProductivity',
    'Compute productivity',
    'ai',
    'per unit',
    0,
    0,
    2,
    'How much one unit of agent compute raises the buying firm’s capacity next month. Capacity is multiplied by one plus this rate times units bought last month. At 0 the purchase is only a payment and capacity is unchanged, which reproduces the previous production path. Above 0, firms that buy compute produce more.',
  ),
  numberSlider(
    'ai.paymentFrictionFiat',
    'Fiat payment friction',
    'aiClaims',
    'share per transaction',
    0.02,
    0,
    0.1,
    'Fee on an AI agent sale in the fiat regime, as a share of the payment. The fee is paid into bank equity. The asking price rises along the adoption curve toward 4 percent of the wage and is marked up by this fee. Firms buy only when the ask is still under 4.2 percent of the wage, so a fee of about 5 percent or more stops the sales once output is near that ceiling. Below that, a higher fee makes the agent a worse deal and can leave the ask uncompetitive. The bitcoin and hybrid regimes use the bitcoin fee instead. The fee does nothing when no agents are created.',
  ),
  numberSlider(
    'ai.paymentFrictionBitcoin',
    'Bitcoin payment friction',
    'aiClaims',
    'share per transaction',
    0.005,
    0,
    0.1,
    'Fee on an AI agent sale in the bitcoin and hybrid regimes, as a share of the payment. The fee is paid into bank equity. The asking price rises along the adoption curve toward 4 percent of the wage and is marked up by this fee. Firms buy only when the ask is still under 4.2 percent of the wage, so a fee of about 5 percent or more stops the sales once output is near that ceiling. The default of 0.005 stays well under that cutoff. The fiat regime uses the fiat fee instead. The fee does nothing when no agents are created.',
  ),
  numberSlider(
    'agent.marketDepth',
    'Agent market depth',
    'aiClaims',
    'coefficient',
    0,
    0,
    2,
    'How much crowding raises the price of agent compute. The ask starts at the adoption progress times 4 percent of the wage, marked up by payment friction. Above 0 it is multiplied by one plus this depth times agents per firm. Firms still buy only when the ask is under 4.2 percent of the wage, so enough crowding stops the sales. At 0 the ask is unchanged and the previous agent market is reproduced.',
  ),
];
