import type { Slider } from '../builders.js';
import { numberSlider } from '../builders.js';

export const AI_SLIDERS: readonly Slider[] = [
  numberSlider(
    'ai.automatableShareStart',
    'Initial automatable share',
    'ai',
    'share',
    0.1,
    0,
    0.5,
    'Share of tasks software can already do in month zero. Adoption follows an S-curve from this share up to the final automatable share. The final share has to be at least this large. If the two shares are equal, the curve stays put, firms do not adopt AI, and production, hiring, and ownership stay on the path with no AI effect.',
  ),
  numberSlider(
    'ai.automatableShareEnd',
    'Final automatable share',
    'ai',
    'share',
    0.9,
    0.3,
    1,
    'Share of tasks software can do once the adoption curve has finished. Only the rise from the starting share can be adopted, and only the non-physical part of that rise adds capacity. While adoption is underway and capacity has actually increased, a household whose skill is below the current automatable share may apply to only one firm a month.',
  ),
  numberSlider(
    'ai.adoptionMidpointYear',
    'AI adoption midpoint',
    'ai',
    'years',
    15,
    3,
    40,
    'Year when the automatable share is halfway from the start share to the end share. An earlier year brings the S-curve forward. The curve is flat, and this year does nothing, when the start and end shares are equal.',
  ),
  numberSlider(
    'ai.adoptionSteepness',
    'AI adoption steepness',
    'ai',
    '1/year',
    0.4,
    0.1,
    1.5,
    'How sharply the automatable share climbs through its S-curve, per year. A higher value bunches the change around the midpoint year. A lower value spreads the same change over more years. It has no effect when the start and end shares are equal.',
  ),
  numberSlider(
    'ai.computeCostDeclineRate',
    'Compute cost decline',
    'ai',
    '1/year',
    0.3,
    0,
    0.6,
    'Annual rate at which AI compute gets cheaper. Cost starts equal to the wage and is multiplied by one minus this rate each year. Firms take up newly automatable tasks only once that cost is below the wage. Any positive rate makes cost fall below the wage after the first year. At zero, cost stays at the wage and this channel adds no capacity.',
  ),
  numberSlider(
    'ai.physicalTaskShare',
    'Physical task share',
    'ai',
    'share',
    0.3,
    0,
    0.7,
    'Share of tasks that software cannot do, such as in-person physical work. Extra capacity from AI is the gain in the automatable share times one minus this share. If the automatable share has risen by 0.2 and this share is 0.3, capacity is about 14 percent higher. At 0, the whole gain becomes capacity. At 1, nothing is automated. Displacement, which limits job search, begins only once capacity has actually increased.',
  ),
  numberSlider(
    'ai.ownershipConcentration',
    'AI ownership concentration',
    'ai',
    'share',
    0.8,
    0.1,
    0.99,
    'How concentrated the gains from AI are across households. Two things use it. Profit shares normally follow skill raised to 1.5; once AI capacity is above normal, that exponent rises by this value times the extra capacity factor, so the same skill gaps claim a larger share of profits. AI agents are also owned by a smaller group: the owner count is the household count times one minus this value. At 0.8, about a fifth of households own the agents. It does not change who is employed.',
  ),
  numberSlider(
    'ai.agentAutonomyShareEnd',
    'AI agent autonomy share',
    'ai',
    'share',
    0.5,
    0,
    1,
    'How many AI agents eventually keep their own accounts, as a share of the household count. The count rises in a straight line from zero to this share over five years. At 0.5 with 1,000 households, the run ends with about 500 agents. Each agent has a human owner, holds a deposit, and sells one unit of compute to a firm when its price, including the payment fee, is cheap relative to the wage. It keeps a small amount for compute and pays the rest to its owner. Human well-being, income, and wealth count households only. At zero, no agents are created and the rest of the economy is unchanged.',
  ),
  numberSlider(
    'ai.paymentFrictionFiat',
    'Fiat payment friction',
    'ai',
    'share per transaction',
    0.02,
    0,
    0.1,
    'Fee on an AI agent sale in the fiat regime, as a share of the payment. The fee is paid into bank equity. The asking price starts at 4 percent of the wage and is marked up by this fee. Firms buy only when the ask is still under 4.2 percent of the wage, so a fee of about 5 percent or more stops the sales. Below that, a higher fee makes the agent a worse deal and can leave the ask uncompetitive. The bitcoin and hybrid regimes use the bitcoin fee instead. The fee does nothing when no autonomous agents are created.',
  ),
  numberSlider(
    'ai.paymentFrictionBitcoin',
    'Bitcoin payment friction',
    'ai',
    'share per transaction',
    0.005,
    0,
    0.1,
    'Fee on an AI agent sale in the bitcoin and hybrid regimes, as a share of the payment. The fee is paid into bank equity. The asking price starts at 4 percent of the wage and is marked up by this fee. Firms buy only when the ask is still under 4.2 percent of the wage, so a fee of about 5 percent or more stops the sales. The default of 0.005 stays well under that cutoff. The fiat regime uses the fiat fee instead. The fee does nothing when no autonomous agents are created.',
  ),
];
