import type { Slider } from '../builders.js';
import { numberSlider } from '../builders.js';

export const AI_SLIDERS: readonly Slider[] = [
  numberSlider(
    'ai.automatableShareStart',
    'Initial automatable share',
    'aiAdoption',
    'share',
    0.1,
    0,
    0.5,
    'Share of tasks software can already do in month zero. Adoption follows an S-curve from this share up to the final automatable share. The final share has to be at least this large. If the two shares are equal, the curve stays put, firms do not adopt AI, and production, hiring, and ownership stay on the path with no AI effect.',
  ),
  numberSlider(
    'ai.automatableShareEnd',
    'Final automatable share',
    'aiAdoption',
    'share',
    0.9,
    0.3,
    1,
    'Share of tasks software can do once the adoption curve has finished. Only the rise from the starting share can be adopted, and only the non-physical part of that rise adds capacity. While adoption is underway and capacity has actually increased, a household whose skill is below the current automatable share may apply to only one firm a month.',
  ),
  numberSlider(
    'ai.adoptionMidpointYear',
    'AI adoption midpoint',
    'aiAdoption',
    'years',
    15,
    3,
    40,
    'Year when the automatable share is halfway from the start share to the end share. An earlier year brings the S-curve forward. The curve is flat, and this year does nothing, when the start and end shares are equal.',
  ),
  numberSlider(
    'ai.adoptionSteepness',
    'AI adoption steepness',
    'aiAdoption',
    '1/year',
    0.4,
    0.1,
    1.5,
    'How sharply the automatable share climbs through its S-curve, per year. A higher value bunches the change around the midpoint year. A lower value spreads the same change over more years. It has no effect when the start and end shares are equal.',
  ),
  numberSlider(
    'ai.computeCostDeclineRate',
    'Compute cost decline',
    'aiAdoption',
    '1/year',
    0.3,
    0,
    0.6,
    'Annual rate at which AI compute gets cheaper. Cost starts equal to the wage and is multiplied by one minus this rate each year. Firms take up newly automatable tasks only once that cost is below the wage. Any positive rate makes cost fall below the wage after the first year. At zero, cost stays at the wage and this channel adds no capacity.',
  ),
  numberSlider(
    'ai.physicalTaskShare',
    'Physical task share',
    'aiReach',
    'share',
    0.3,
    0,
    0.7,
    'Share of tasks that software cannot do, such as in-person physical work, before the robotics ramp opens them. Extra capacity from AI is the gain in the automatable share times one minus the effective physical share. If the automatable share has risen by 0.2 and this share is 0.3, capacity is about 14 percent higher while the ceiling is intact. At 0, the whole gain becomes capacity. At 1, nothing is automated until robots retire the share. Displacement, which limits job search, begins only once capacity has actually increased.',
  ),
  numberSlider(
    'ai.bullishness',
    'AI bullishness',
    'aiBullishness',
    'index',
    1,
    0,
    2,
    'How large the productivity gain is on each adopted task. At 0 the gain is one tenth of the default, about the scale of a decade of internet-era productivity gains once the adoption curve finishes, and unemployment barely moves. At 1, the default, each adopted task adds its full share to capacity and the gain saturates with the S-curve. Above 1 the same level formula compounds: each point above 1 adds 15 percent a year of growth to the task gain with no ceiling, so at 2 the gain grows at 15 percent a year. Hiring still follows the adopted task share, capped by the physical-task share until robots open it. Equal start and end automatable shares still turn the whole AI channel off. The anchors are a modeling guess after Korinek et al. 2026 and the internet-era productivity literature.',
  ),
  numberSlider(
    'ai.roboticsStartYear',
    'Robotics start',
    'aiReach',
    'years',
    5,
    0,
    50,
    'Year from the start of the run when mass robotics begins to open physical tasks. The core does not read the calendar. Tick 0 is month 0, and charts label that month as the month the page is opened, so the default of 5 is about 2031 when month 0 is read as late 2026. Until this year the physical-task share stays at its slider. A start year at or past the last year of the run leaves the ceiling intact for that run.',
  ),
  numberSlider(
    'ai.roboticsRampYears',
    'Robotics ramp',
    'aiReach',
    'years',
    8,
    1,
    30,
    'How many years the effective physical-task share takes to fall from its slider value to zero after the robotics start year. The path is a straight line. At the defaults the ceiling is intact through year 5, half gone around year 9, and gone by year 13. A finished ramp lets the automatable share that software already reached cover the old physical tasks as well. Tasks outside the final automatable share stay human.',
  ),
  numberSlider(
    'ai.ownershipConcentration',
    'AI ownership concentration',
    'aiClaims',
    'share',
    0.8,
    0.1,
    0.99,
    'How concentrated the gains from AI are across households. Two things use it. Profit shares normally follow skill raised to 1.5; once AI capacity is above normal, that exponent rises by this value times the extra capacity factor, so the same skill gaps claim a larger share of profits. AI agents are also owned by a smaller group: the owner count is the household count times one minus this value. At 0.8, about a fifth of households own the agents. It does not change who is employed.',
  ),
  numberSlider(
    'ai.agentAutonomyShareEnd',
    'AI agent autonomy share',
    'aiClaims',
    'share',
    0.5,
    0,
    1,
    'How many AI agents eventually keep their own accounts, as a share of the household count. The count rises in a straight line from zero to this share over five years. At 0.5 with 1,000 households, the run ends with about 500 agents. Each agent has a human owner, holds a deposit, and sells one unit of compute to a firm when its price, including the payment fee, is cheap relative to the wage. It keeps a small amount for compute and pays the rest to its owner. Human well-being, income, and wealth count households only. At zero, no agents are created and the rest of the economy is unchanged.',
  ),
  numberSlider(
    'ai.paymentFrictionFiat',
    'Fiat payment friction',
    'aiClaims',
    'share per transaction',
    0.02,
    0,
    0.1,
    'Fee on an AI agent sale in the fiat regime, as a share of the payment. The fee is paid into bank equity. The asking price starts at 4 percent of the wage and is marked up by this fee. Firms buy only when the ask is still under 4.2 percent of the wage, so a fee of about 5 percent or more stops the sales. Below that, a higher fee makes the agent a worse deal and can leave the ask uncompetitive. The bitcoin and hybrid regimes use the bitcoin fee instead. The fee does nothing when no autonomous agents are created.',
  ),
  numberSlider(
    'ai.paymentFrictionBitcoin',
    'Bitcoin payment friction',
    'aiClaims',
    'share per transaction',
    0.005,
    0,
    0.1,
    'Fee on an AI agent sale in the bitcoin and hybrid regimes, as a share of the payment. The fee is paid into bank equity. The asking price starts at 4 percent of the wage and is marked up by this fee. Firms buy only when the ask is still under 4.2 percent of the wage, so a fee of about 5 percent or more stops the sales. The default of 0.005 stays well under that cutoff. The fiat regime uses the fiat fee instead. The fee does nothing when no autonomous agents are created.',
  ),
];
