import type { Slider } from '../builders.js';
import { enumSlider, numberSlider } from '../builders.js';

export const BEHAVIOR_SLIDERS: readonly Slider[] = [
  numberSlider(
    'household.timePreferenceMean',
    'Mean time preference',
    'behavior',
    '1/year',
    0.04,
    0.01,
    0.15,
    'How impatient households are, on average, as an annual discount rate. Each household draws a rate around this mean, and the draw is kept between 1 and 15 percent a year. Spending depends on whether a household is more or less impatient than this mean, so raising the mean does not raise average spending. Inflation above the regime path can still raise average spending through household.inflationTimePreference. In the fiat regime the same number is the neutral real interest rate: the policy rate starts from this value plus inflation. A higher mean lifts the fiat policy rate even when inflation is on target.',
  ),
  numberSlider(
    'household.timePreferenceStd',
    'Time preference spread',
    'behavior',
    '1/year',
    0.02,
    0,
    0.08,
    'How widely patience differs across households. Each household draws a normal rate around the mean time preference, then the draw is kept between 1 and 15 percent a year. A household above the mean spends a larger share of smoothed income; one below the mean saves more. A wider spread fans consumption and deposit balances apart. At zero, every household has the mean rate and no patience draw is used.',
  ),
  numberSlider(
    'household.inflationTimePreference',
    'Inflation time-preference response',
    'behavior',
    'coefficient',
    0.1,
    0,
    0.5,
    'How strongly inflation above the regime normal path raises the goods spending share. The gap is expected inflation minus the inflation target under fiat, or minus productivity growth under bitcoin and hybrid. Expected inflation is the trailing year-over-year rate unless expectations.anchorWeight pulls it toward that path. The share rises by this coefficient times the gap. At 0.1, ten percentage points of inflation above the path raises the share by one percentage point. The response is small because value can sit in assets other than goods, so only a leak into consumption shows up here. At 0 the spending share ignores inflation. The fiat policy rate still uses the mean time-preference slider alone.',
  ),
  numberSlider(
    'expectations.anchorWeight',
    'Inflation anchor',
    'behavior',
    'share',
    0,
    0,
    1,
    'How far expected inflation follows the regime path instead of the last year of prices. The path is the inflation target under fiat and minus baseline productivity under bitcoin and hybrid. Expected inflation is this weight times that path plus one minus the weight times trailing inflation. Spending, the real return on money, the deflation penalty, contract choice, and the fiat policy rate use that expectation. Posted-price and wage trends keep the regime path at weight 0, and follow the expectation above 0. At 0 every expectation is the trailing rate, which reproduces the previous phase. At 1 expectations sit on the regime path.',
  ),
  numberSlider(
    'household.openingDepositMonths',
    'Opening deposit months',
    'behavior',
    'months',
    36,
    6,
    60,
    'Months of the base wage, scaled by skill squared, held as each household’s opening deposit. At 36, deposits are about three years of income and velocity is low. Lower values raise velocity. The monetary preset can shorten this toward a year of income.',
  ),
  numberSlider(
    'household.skillSigma',
    'Skill dispersion',
    'behavior',
    'log points',
    0.5,
    0.1,
    1.2,
    'Spread of innate earning power, as the standard deviation of a lognormal skill draw. Draws are kept between 0.2 and 5, then divided by their average so mean skill is 1. A worker is paid the firm wage times skill. Starting deposits scale with skill squared, about three years of the base wage for a skill of 1, so wealth begins more unequal than pay. Profits are shared with weights of skill raised to 1.5 or more, which concentrates capital income on high-skill households. A larger value thickens the high-skill tail.',
  ),
  numberSlider(
    'household.realReturnSensitivity',
    'Real-return spending sensitivity',
    'behavior',
    'coefficient',
    0,
    0,
    5,
    'How strongly a positive real return on money cuts discretionary goods spending. The real return is the deposit rate minus year-over-year inflation. Deposits pay nothing until the deposit pass-through slider is raised, so under deflation the return equals the absolute inflation rate. The household budget from income and deposits is split into a food and housing floor, about 58 percent of the basket, and a discretionary remainder. Only the remainder shrinks: it is multiplied by max(0, 1 − this sensitivity × the real return). The floor is still bought. At 0 the whole budget is unchanged. Credit-financed discretionary spending is a later mechanism.',
  ),
  numberSlider(
    'firm.markup',
    'Firm markup',
    'behavior',
    'share of cost',
    0.2,
    0.05,
    0.6,
    'How far the target price sits above unit labor cost. The target is unit cost times one plus this markup, times a small inventory adjustment of at most 2 percent. A markup of 0.2 means the target is 20 percent above cost. Posted prices drift toward that target; they do not jump to it. The opening price level is the starting wage times one plus this markup.',
  ),
  numberSlider(
    'firm.priceAdjustSpeed',
    'Price adjustment speed',
    'behavior',
    'share per tick',
    0.3,
    0.05,
    1,
    'How strongly the price is pulled toward the cost target each month. The pull is this speed times 1 percent of the gap between the target and the current price, and it is capped at 0.1 percent a month, so a speed of 1 still cannot reprice faster than that cap. Low inventory raises the target and high inventory lowers it. Raising the speed closes the gap to cost sooner. The inflation trend, set by the regime, is separate from this pull.',
  ),
  enumSlider(
    'firm.investmentHurdle',
    'Investment hurdle',
    'behavior',
    'mode',
    'off',
    ['off', 'on'],
    'Whether firms install capital only when the expected return clears the real return on money plus a premium. Off keeps the scheduled capital rule and the profit-sharing formula tied to the deflation penalty. On: expected return is baseline productivity growth plus a quarter of the firm markup. The real return on money is the deposit rate minus inflation. If the project clears, capital is installed as before. If it fails, only a quarter of the gap is installed from retained claims and the rest is recorded as profit-sharing finance. Measured profit-sharing share is profit-sharing finance over that plus loan-path finance.',
  ),
  numberSlider(
    'firm.hurdlePremium',
    'Investment hurdle premium',
    'behavior',
    '1/year',
    0.02,
    0,
    0.1,
    'Extra real return a capital project must earn above the real return on money when the investment hurdle is on. At 0.02 the project must beat money by two percentage points a year. Unused when the hurdle is off.',
  ),
  numberSlider(
    'prices.trendWeight',
    'Price trend weight',
    'behavior',
    'share',
    1,
    0,
    1,
    'Share of monthly price growth that follows the regime price trend. The rest follows excess demand: desired goods spending this month relative to nominal capacity, minus one. Monthly growth is this weight times the trend plus one minus this weight times excess demand, plus the small cost nudge and shock tilt, then capped. At 1 the posted-price rule is unchanged and the fiat inflation target or bitcoin productivity trend still writes the path. At 0 prices move only with excess demand, so a shortfall can pull the CPI down even when the regime trend is positive.',
  ),
  numberSlider(
    'wage.nominalRigidity',
    'Nominal wage rigidity',
    'behavior',
    'share',
    0.7,
    0,
    0.95,
    'How sticky the money wage is when unemployment is away from the natural rate. The natural rate starts at 6 percent and rises as AI raises capacity, because the hiring target shrinks with the human share of output. Wages still follow monthly inflation and productivity growth. An extra gap opens when the labor market is tight or slack relative to that natural rate, the gap is scaled by the human share of output, and this rigidity shrinks it further. Upward pressure is multiplied by one minus the rigidity. Downward pressure is multiplied by the square of that remainder, so cuts pass through less than raises. At 0.7, a tight market passes through 30 percent of the upward gap and 9 percent of a downward gap. At 0, the gap passes through in full. The monthly wage change is still capped.',
  ),
  enumSlider(
    'equity.marketOn',
    'Equity market',
    'behavior',
    'switch',
    'on',
    ['off', 'on'],
    'Whether household wealth includes a claim on firm capital. On, firm capital valued at the posted price is split across households with the same skill weights used for profits, including the extra concentration from AI ownership. Those claims are not traded and do not move deposits. They raise measured wealth and the wealth Gini when capital income is uneven. Off counts only deposits.',
  ),
];
