import type { Slider } from '../builders.js';
import { numberSlider } from '../builders.js';

export const BEHAVIOR_SLIDERS: readonly Slider[] = [
  numberSlider(
    'household.timePreferenceMean',
    'Mean time preference',
    'behavior',
    '1/year',
    0.04,
    0.01,
    0.15,
    'How impatient households are, on average, as an annual discount rate. Each household draws a rate around this mean, and the draw is kept between 1 and 15 percent a year. Spending depends on whether a household is more or less impatient than this mean, so raising the mean does not raise average spending. In the fiat regime the same number is the neutral real interest rate: the policy rate starts from this value plus inflation. A higher mean lifts the fiat policy rate even when inflation is on target.',
  ),
  numberSlider(
    'household.timePreferenceStd',
    'Time preference spread',
    'behavior',
    '1/year',
    0.02,
    0,
    0.08,
    'How widely patience differs across households. Each household draws a normal rate around the mean time preference, then the draw is kept between 1 and 15 percent a year. A household above the mean spends a larger share of smoothed income; one below the mean saves more. A wider spread fans consumption and deposit balances apart. At zero, every household has the mean rate and no patience draw is used.',
  ),
  numberSlider(
    'household.skillSigma',
    'Skill dispersion',
    'behavior',
    'log points',
    0.5,
    0.1,
    1.2,
    'Spread of innate earning power, as the standard deviation of a lognormal skill draw. Draws are kept between 0.2 and 5, then divided by their average so mean skill is 1. A worker is paid the firm wage times skill. Starting deposits scale with skill squared, about three years of the base wage for a skill of 1, so wealth begins more unequal than pay. Profits are shared with weights of skill raised to 1.5 or more, which concentrates capital income on high-skill households. A larger value thickens the high-skill tail.',
  ),
  numberSlider(
    'household.trustInBanks',
    'Trust in banks',
    'behavior',
    'share',
    0.9,
    0,
    1,
    'Intended share of households willing to keep money in bank deposits rather than cash. The economy does not read this slider. Moving it does not change deposits, lending, or prices. It is stored with the scenario so the assumption stays visible.',
  ),
  numberSlider(
    'firm.markup',
    'Firm markup',
    'behavior',
    'share of cost',
    0.2,
    0.05,
    0.6,
    'How far the target price sits above unit labor cost. The target is unit cost times one plus this markup, times a small inventory adjustment of at most 2 percent. A markup of 0.2 means the target is 20 percent above cost. Posted prices drift toward that target; they do not jump to it. The opening price level is the starting wage times one plus this markup.',
  ),
  numberSlider(
    'firm.priceAdjustSpeed',
    'Price adjustment speed',
    'behavior',
    'share per tick',
    0.3,
    0.05,
    1,
    'How strongly the price is pulled toward the cost target each month. The pull is this speed times 1 percent of the gap between the target and the current price, and it is capped at 0.1 percent a month, so a speed of 1 still cannot reprice faster than that cap. Low inventory raises the target and high inventory lowers it. Raising the speed closes the gap to cost sooner. The inflation trend, set by the regime, is separate from this pull.',
  ),
  numberSlider(
    'wage.nominalRigidity',
    'Nominal wage rigidity',
    'behavior',
    'share',
    0.7,
    0,
    0.95,
    'How sticky the money wage is when unemployment is away from the natural rate. The natural rate starts at 6 percent and rises as AI raises capacity, because the hiring target shrinks with the human share of output. Wages still follow monthly inflation and productivity growth. An extra gap opens when the labor market is tight or slack relative to that natural rate, the gap is scaled by the human share of output, and this rigidity shrinks it further. Upward pressure is multiplied by one minus the rigidity. Downward pressure is multiplied by the square of that remainder, so cuts pass through less than raises. At 0.7, a tight market passes through 30 percent of the upward gap and 9 percent of a downward gap. At 0, the gap passes through in full. The monthly wage change is still capped.',
  ),
];
