import type { Slider } from '../builders.js';
import { enumSlider, numberSlider } from '../builders.js';

export const BEHAVIOR_SLIDERS: readonly Slider[] = [
  numberSlider(
    'household.timePreferenceMean',
    'Mean time preference',
    'behavior',
    '1/year',
    0.04,
    0.01,
    0.15,
    'How impatient households are, on average, as an annual discount rate. Each household draws a rate around this mean, and the draw is kept between 1 and 15 percent a year. Spending depends on whether a household is more or less impatient than this mean, so raising the mean does not raise average spending. Inflation above the regime path can still raise average spending through household.inflationTimePreference. In the fiat regime the same number is the neutral real interest rate: the policy rate starts from this value plus inflation. A higher mean lifts the fiat policy rate even when inflation is on target.',
  ),
  numberSlider(
    'household.timePreferenceStd',
    'Time preference spread',
    'behavior',
    '1/year',
    0.02,
    0,
    0.08,
    'How widely patience differs across households. Each household draws a normal rate around the mean time preference, then the draw is kept between 1 and 15 percent a year. A household above the mean spends a larger share of smoothed income; one below the mean saves more. A wider spread fans consumption and deposit balances apart. At zero, every household has the mean rate and no patience draw is used.',
  ),
  numberSlider(
    'household.inflationTimePreference',
    'Inflation time-preference response',
    'behavior',
    'coefficient',
    0.1,
    0,
    0.5,
    'How strongly inflation above the regime normal path raises the goods spending share. The gap is expected inflation minus the inflation target under fiat, or minus productivity growth under bitcoin and hybrid. Expected inflation is the trailing year-over-year rate unless expectations.anchorWeight pulls it toward that path. The share rises by this coefficient times the gap. At 0.1, ten percentage points of inflation above the path raises the share by one percentage point. The response is small because value can sit in assets other than goods, so only a leak into consumption shows up here. At 0 the spending share ignores inflation. The fiat policy rate still uses the mean time-preference slider alone.',
  ),
  numberSlider(
    'expectations.anchorWeight',
    'Inflation anchor',
    'behavior',
    'share',
    0.65,
    0,
    1,
    'How far expected inflation follows the regime path instead of the last year of prices. The path is the inflation target under fiat and minus baseline productivity under bitcoin and hybrid. Expected inflation is this weight times that path plus one minus the weight times trailing inflation. Spending, the real return on money, the deflation penalty, contract choice, and the fiat policy rate use that expectation. Posted-price trends keep the regime path at weight 0, and follow the expectation above 0. Wages negotiate toward the agreed wage from the price level and do not take this path directly. The default of 0.65 puts most weight on the regime path. At 0 every expectation is the trailing rate. At 1 expectations sit on the regime path.',
  ),
  numberSlider(
    'household.openingDepositMonths',
    'Opening deposit months',
    'behavior',
    'months',
    18,
    6,
    60,
    'Months of the base wage, scaled by skill squared, held as each household’s opening deposit. The default of 18 is about a year and a half of income. Lower values raise velocity. At 36 deposits are about three years of income and velocity is low.',
  ),
  numberSlider(
    'household.skillSigma',
    'Skill dispersion',
    'behavior',
    'log points',
    0.7,
    0.1,
    1.2,
    'Spread of innate earning power, as the standard deviation of a lognormal skill draw. Draws are kept between 0.2 and 5, then divided by their average so mean skill is 1. A worker is paid the firm wage times skill. Starting deposits scale with skill squared, about the opening-deposit months of the base wage for a skill of 1, so wealth begins more unequal than pay. Profits are shared with weights of skill raised to 1.5 or more, which concentrates capital income on high-skill households. The default of 0.7 thickens the high-skill tail relative to 0.5.',
  ),
  numberSlider(
    'household.realReturnSensitivity',
    'Real-return spending sensitivity',
    'behavior',
    'coefficient',
    0.8,
    0,
    5,
    'How strongly a positive real return on money cuts discretionary goods spending. The real return is the deposit rate minus year-over-year inflation. The household budget from income and deposits is split into a food and housing floor, about 58 percent of the basket, and a discretionary remainder. Only the remainder shrinks: it is multiplied by max(0, 1 − this sensitivity × the real return). The floor is still bought. The default of 0.8 cuts discretionary spending when money pays a real return. At 0 the whole budget is unchanged.',
  ),
  numberSlider(
    'firm.markup',
    'Firm markup',
    'behavior',
    'share of cost',
    0.2,
    0.05,
    0.6,
    'How far the target price sits above unit labor cost. The target is unit cost times one plus this markup, times a small inventory adjustment of at most 2 percent. A markup of 0.2 means the target is 20 percent above cost. Posted prices drift toward that target; they do not jump to it. The opening price level is the starting wage times one plus this markup.',
  ),
  numberSlider(
    'firm.priceAdjustSpeed',
    'Price adjustment speed',
    'behavior',
    'share per tick',
    0.3,
    0.05,
    1,
    'How strongly the price is pulled toward the cost target each month. The pull is this speed times 1 percent of the gap between the target and the current price, and it is capped at 0.1 percent a month, so a speed of 1 still cannot reprice faster than that cap. Low inventory raises the target and high inventory lowers it. Raising the speed closes the gap to cost sooner. The inflation trend, set by the regime, is separate from this pull.',
  ),
  enumSlider(
    'firm.investmentHurdle',
    'Investment hurdle',
    'behavior',
    'mode',
    'on',
    ['off', 'on'],
    'Whether firms install capital only when the expected return clears the real return on money plus a premium. On: expected return is baseline productivity growth plus a quarter of the firm markup. The real return on money is the deposit rate minus inflation. If the project clears, capital is installed as before. If it fails, only a quarter of the gap is installed from retained claims and the rest is recorded as profit-sharing finance. Measured profit-sharing share is profit-sharing finance over that plus loan-path finance. Off keeps the scheduled capital rule and the profit-sharing formula tied to the deflation penalty.',
  ),
  numberSlider(
    'firm.hurdlePremium',
    'Investment hurdle premium',
    'behavior',
    '1/year',
    0.02,
    0,
    0.1,
    'Extra real return a capital project must earn above the real return on money when the investment hurdle is on. At 0.02 the project must beat money by two percentage points a year. Unused when the hurdle is off.',
  ),
  numberSlider(
    'prices.trendWeight',
    'Price trend weight',
    'behavior',
    'share',
    0.75,
    0,
    1,
    'Share of monthly price growth that follows the regime price trend. The rest follows excess demand: desired goods spending this month relative to nominal capacity, minus one. Monthly growth is this weight times the trend plus one minus this weight times excess demand, plus the small cost nudge and shock tilt, then capped. The default of 0.75 keeps most of the regime path and lets demand move a quarter of the growth. At 1 the fiat inflation target or bitcoin productivity trend writes the path alone. At 0 prices move only with excess demand.',
  ),
  numberSlider(
    'wage.nominalRigidity',
    'Nominal wage rigidity',
    'behavior',
    'share',
    0.9,
    0,
    0.95,
    'Share of the gap between the posted money wage and the agreed wage left for next month. The agreed wage is the price level times 1 / (1 + firm markup) times economy-wide productivity times one plus 0.4 times labor-market tightness. Employees close a shortfall and employers close an excess at the same speed: one minus this rigidity of the gap each month, capped by the monthly wage move. At 0.9, ten percent of the gap closes each month. At 0 the posted wage matches the agreed wage immediately. Under fiat, whenever trailing inflation is already above the target, upward catch-up is scaled by clamp(1 − 0.5 × overshoot / target, 0.5, 1), so catch-up slows but never freezes. Under rising prices the lag leaves employees behind; under falling prices it leaves them ahead.',
  ),
  enumSlider(
    'equity.marketOn',
    'Equity market',
    'behavior',
    'switch',
    'on',
    ['off', 'on'],
    'Whether household wealth includes a claim on firm capital. On, firm capital valued at the posted price is split across households with the same skill weights used for profits, including the extra concentration from AI ownership. Those claims are not traded and do not move deposits. They raise measured wealth and the wealth Gini when capital income is uneven. Off counts only deposits.',
  ),
];
