import type { Slider } from '../builders.js';
import { basketProductivity, enumSlider, numberSlider } from '../builders.js';

export const GOODS_SLIDERS: readonly Slider[] = [
  numberSlider(
    'goods.electronicsProductivity',
    'Electronics productivity growth',
    'goods',
    '1/year',
    0.08,
    0,
    0.3,
    'Annual productivity growth of electronics, used only to split the CPI. After t years the unscaled electronics price relative to baseline productivity is ((1 + baseline productivity growth) / (1 + this rate)) raised to t. Electronics are about 1 percent of the basket. The shares follow the U.S. CPI-U for December 2024, with energy taken out of housing and transportation and the listed categories rescaled so they sum to one. The basket is then scaled so the expenditure-weighted average equals the CPI. A higher rate makes electronics cheaper relative to the CPI. It does not produce extra goods or open a separate shop. Set every category productivity and housing supply growth equal to baseline productivity to put every price on the CPI.',
  ),
  basketProductivity(
    'goods.foodProductivity',
    'Food and bev',
    'about 15 percent',
    0.01,
    'The default equals baseline productivity.',
  ),
  numberSlider(
    'goods.housingSupplyGrowth',
    'Housing supply growth',
    'goods',
    '1/year',
    0,
    -0.01,
    0.02,
    'Annual growth in the supply of housing. Demand is taken to rise with real income, so the unscaled housing price is ((1 + baseline productivity growth) / (1 + this rate)) raised to t, times one minus the deflation penalty. Housing is about 43 percent of the basket, the December 2024 CPI-U housing share with household energy removed, then rescaled with the other categories. The basket is scaled so the expenditure-weighted average equals the CPI. Expected deflation cuts housing demand through the penalty. A higher housing price relative to the CPI lowers housing security. At zero, housing rises with productivity. A negative rate means the stock shrinks. Set this equal to baseline productivity, and set every category productivity equal to that same baseline, to put every price on the CPI aside from the deflation term. When housing.marketClearing is on, this growth also eases the market scarcity index.',
  ),
  enumSlider(
    'housing.marketClearing',
    'Housing market clearing',
    'goods',
    'switch',
    'off',
    ['off', 'on'],
    'Whether housing scarcity is a market outcome. Off keeps the formula price and a home price of 48 months of income. On, scarcity starts at 1 and moves with the share of households who own or hold a mortgage, and with housing supply growth. That scarcity multiplies the housing category price and the home price used for tenure choice. When tenure choice is off, demand sits at the neutral share, so scarcity stays at 1 unless supply growth moves it. Off reproduces the previous housing prices.',
  ),
  basketProductivity(
    'goods.energyProductivity',
    'Energy',
    'about 7 percent',
    0.005,
    'The default is below baseline, so energy rises relative to it, and by less than housing.',
  ),
  basketProductivity(
    'goods.apparelProductivity',
    'Apparel',
    'about 3 percent',
    0.04,
    'The default is above baseline, so apparel cheapens.',
  ),
  basketProductivity(
    'goods.transportProductivity',
    'Transportation',
    'about 14 percent',
    0.02,
    'The default is a little above baseline, so transportation cheapens slowly. Motor fuel is in energy, not here.',
  ),
  basketProductivity(
    'goods.medicalProductivity',
    'Medical',
    'about 9 percent',
    0.003,
    'The default is below baseline, so medical care rises relative to it.',
  ),
  basketProductivity(
    'goods.educationProductivity',
    'Education',
    'about 3 percent',
    0.001,
    'The default is just below baseline, so education rises slightly relative to it. Communication is not in this share.',
  ),
  basketProductivity(
    'goods.recreationProductivity',
    'Recreation',
    'about 6 percent',
    0.03,
    'The default is above baseline, so recreation cheapens.',
  ),
  numberSlider(
    'deflation.sensitivity',
    'Deflation sensitivity',
    'credit',
    'coefficient',
    1,
    0,
    5,
    'How strongly expected deflation changes credit and housing. Expected deflation is zero when inflation is positive, and the absolute value of inflation when prices are falling. The penalty is this sensitivity times that rate, capped at 0.9. While it is positive, firms repay a slice of their loans each month, housing demand is scaled down by the penalty, and the reported profit-sharing and non-mortgage housing shares rise when tenure choice is off. When tenure choice is on, those housing shares are measured from household tenures instead. At zero, or whenever inflation is positive, the penalty is off, so a fiat run near the inflation target is unchanged.',
  ),
  enumSlider(
    'housing.tenureChoice',
    'Housing tenure choice',
    'credit',
    'mode',
    'off',
    ['off', 'on'],
    'Whether households choose rent, a nominal mortgage, or cash ownership. Off keeps the penalty formulas for non-mortgage housing and property turnover, and households hold no mortgages or consumer loans. On: households open already housed at the opening owner share, then each month pick the tenure with the lowest expected real burden. Expected deflation raises the mortgage burden, so fewer new mortgages are taken. Shelter stays inside the food and housing spending floor. Consumer loans fund only discretionary spending above that floor and fall as the deflation penalty rises, down to zero. Household loans count in total credit and the bank capital rule.',
  ),
  numberSlider(
    'housing.adjustmentRate',
    'Tenure adjustment rate',
    'credit',
    '1/month',
    0.01,
    0,
    1,
    'Share of households who may switch tenure in one month when tenure choice is on. Each household draws against its own stream, so a cheap loan rate cannot move the whole eligible stock in the opening tick. Opening tenure is unchanged until a household draws a switch. At 1 every household reconsiders every month. At 0 tenure stays at the opening mix. Unused when tenure choice is off.',
  ),
  numberSlider(
    'housing.openingOwnerShare',
    'Opening owner share',
    'credit',
    'share',
    0.655,
    0,
    1,
    'Share of households who already own a home when tenure choice is on. The default of 0.655 is the approximate U.S. homeownership rate in 2026, so about 34.5 percent start as renters. The highest-skill households own outright. The next band, set by the mortgage share of owners, holds a nominal mortgage. Everyone else rents. The purchase is not replayed: outright owners have no housing loan, and an opening mortgage is outstanding principal rather than new cash. At 0 every household starts renting. Unused when tenure choice is off.',
  ),
  numberSlider(
    'housing.openingMortgageShareOfOwners',
    'Opening mortgage share of owners',
    'credit',
    'share',
    0.62,
    0,
    1,
    'Share of opening owners who still owe a mortgage when tenure choice is on. The default of 0.62 is about the share of U.S. owner households with a mortgage. With an owner share of 0.655, about 40.6 percent of households start with a mortgage and 24.9 percent own outright. The principal is the loan-to-value share of 48 months of that household’s income, at the opening loan rate and the mortgage term. If that book would leave bank reserves short of the reserve requirement, every principal is scaled down by the same factor. A household whose principal rounds to zero owns outright instead. At 0 every opening owner owns outright. Unused when tenure choice is off.',
  ),
  numberSlider(
    'housing.mortgageTermYears',
    'Mortgage term',
    'credit',
    'years',
    30,
    5,
    40,
    'Length of a new nominal mortgage when tenure choice is on. The monthly payment is the principal divided by the term in months. A longer term lowers the monthly payment and raises the expected real burden under deflation, because the debt is outstanding longer. Unused when tenure choice is off.',
  ),
  numberSlider(
    'housing.mortgageLtv',
    'Mortgage loan-to-value',
    'credit',
    'share',
    0.8,
    0.5,
    0.95,
    'Maximum loan as a share of the home price when tenure choice is on. The home price is 48 months of the household’s income. A higher ratio lets more of the purchase be debt. Unused when tenure choice is off.',
  ),
  numberSlider(
    'housing.consumerCreditLimit',
    'Consumer credit limit',
    'credit',
    'share of income',
    0.2,
    0,
    1,
    'Maximum consumer loan stock as a share of monthly income when tenure choice is on. New borrowing each month is that headroom times one minus the deflation penalty, and it cannot exceed bank lending room. The loan funds discretionary spending only. At 0, no consumer credit is issued. Unused when tenure choice is off.',
  ),
  numberSlider(
    'housing.mortgageDefaultShare',
    'Mortgage default income share',
    'credit',
    'share',
    0.4,
    0.1,
    1,
    'When tenure choice is on, a household that cannot pay its full mortgage for three months while the payment exceeds this share of income has the unpaid balance written off against bank equity and returns to rent. At 0.4 the payment must be above 40 percent of income. Unused when tenure choice is off.',
  ),
];
