import type { Slider } from '../builders.js';
import { basketProductivity, numberSlider } from '../builders.js';

export const GOODS_SLIDERS: readonly Slider[] = [
  numberSlider(
    'goods.electronicsProductivity',
    'Electronics productivity growth',
    'goods',
    '1/year',
    0.08,
    0,
    0.3,
    'Annual productivity growth of electronics, used only to split the CPI. After t years the unscaled electronics price relative to baseline productivity is ((1 + baseline productivity growth) / (1 + this rate)) raised to t. Electronics are about 1 percent of the basket. The shares follow the U.S. CPI-U for December 2024, with energy taken out of housing and transportation and the listed categories rescaled so they sum to one. The basket is then scaled so the expenditure-weighted average equals the CPI. A higher rate makes electronics cheaper relative to the CPI. It does not produce extra goods or open a separate shop. Set every category productivity and housing supply growth equal to baseline productivity to put every price on the CPI.',
  ),
  basketProductivity(
    'goods.foodProductivity',
    'Food and bev',
    'about 15 percent',
    0.01,
    'The default equals baseline productivity.',
  ),
  numberSlider(
    'goods.housingSupplyGrowth',
    'Housing supply growth',
    'goods',
    '1/year',
    0,
    -0.01,
    0.02,
    'Annual growth in the supply of housing. Demand is taken to rise with real income, so the unscaled housing price is ((1 + baseline productivity growth) / (1 + this rate)) raised to t, times one minus the deflation penalty. Housing is about 43 percent of the basket, the December 2024 CPI-U housing share with household energy removed, then rescaled with the other categories. The basket is scaled so the expenditure-weighted average equals the CPI. Expected deflation cuts housing demand through the penalty. A higher housing price relative to the CPI lowers housing security. At zero, housing rises with productivity. A negative rate means the stock shrinks. Set this equal to baseline productivity, and set every category productivity equal to that same baseline, to put every price on the CPI aside from the deflation term.',
  ),
  basketProductivity(
    'goods.energyProductivity',
    'Energy',
    'about 7 percent',
    0.005,
    'The default is below baseline, so energy rises relative to it, and by less than housing.',
  ),
  basketProductivity(
    'goods.apparelProductivity',
    'Apparel',
    'about 3 percent',
    0.04,
    'The default is above baseline, so apparel cheapens.',
  ),
  basketProductivity(
    'goods.transportProductivity',
    'Transportation',
    'about 14 percent',
    0.02,
    'The default is a little above baseline, so transportation cheapens slowly. Motor fuel is in energy, not here.',
  ),
  basketProductivity(
    'goods.medicalProductivity',
    'Medical',
    'about 9 percent',
    0.003,
    'The default is below baseline, so medical care rises relative to it.',
  ),
  basketProductivity(
    'goods.educationProductivity',
    'Education',
    'about 3 percent',
    0.001,
    'The default is just below baseline, so education rises slightly relative to it. Communication is not in this share.',
  ),
  basketProductivity(
    'goods.recreationProductivity',
    'Recreation',
    'about 6 percent',
    0.03,
    'The default is above baseline, so recreation cheapens.',
  ),
  numberSlider(
    'deflation.sensitivity',
    'Deflation sensitivity',
    'contracts',
    'coefficient',
    1,
    0,
    5,
    'How strongly expected deflation changes credit and housing. Expected deflation is zero when inflation is positive, and the absolute value of inflation when prices are falling. The penalty is this sensitivity times that rate, capped at 0.9. While it is positive, firms repay a slice of their loans each month, housing demand is scaled down by the penalty, and the reported profit-sharing and non-mortgage housing shares rise. Those shares are accounting reports. At zero, or whenever inflation is positive, the penalty is off, so a fiat run near the inflation target is unchanged.',
  ),
];
