import type { Slider } from '../builders.js';
import { enumSlider, numberSlider } from '../builders.js';

export const MACRO_SLIDERS: readonly Slider[] = [
  numberSlider(
    'productivity.baseGrowth',
    'Baseline productivity growth',
    'background',
    '1/year',
    0.01,
    0,
    0.04,
    'Annual growth of economy-wide productivity before the AI channels. It compounds into productive capacity and into wage growth. Under bitcoin or hybrid money the price trend is the negative of this rate, because the money stock does not grow with output, so the CPI tends to fall as goods get easier to make. Category prices are measured against this baseline. Match a category productivity, or housing supply growth, to it and that unscaled price stays flat against the baseline. Set every one of them equal to it to put every price on the CPI.',
  ),
  numberSlider(
    'population.growth',
    'Population growth',
    'background',
    '1/year',
    0,
    -0.01,
    0.02,
    'Annual change in the number of households. The monthly rate adds or removes people deterministically, carrying a fractional remainder so a small rate still changes the count. New households enter unemployed, with no deposit, a fresh skill draw, and the next id. A household who exits leaves any deposit to the first household and any loan is written off against bank equity. At 0 the household count stays at the Households slider, which keeps the previous population path. The old default of 0.005 was stored but never applied.',
  ),
  numberSlider(
    'shock.frequency',
    'Shock frequency',
    'shocks',
    '1/year',
    0.1,
    0,
    1,
    'Chance that a new macroeconomic shock starts at a yearly check. Checks begin in month 24 and repeat every 12 months, and a check is skipped while a shock is already running. A value of 0.1 is a 10 percent chance on an idle check. A value of 1 starts a shock whenever the previous one has finished. A value of 0 turns the channel off. Each shock is credit, demand, or productivity with equal chance, and it lasts 24 months: 12 of expansion, then 12 of contraction.',
  ),
  numberSlider(
    'shock.size',
    'Shock size',
    'shocks',
    'share',
    0.05,
    0,
    0.3,
    'Size of a shock while it is active, as a share. A demand shock adds this share to spending and hiring during the expansion year and subtracts half of it during the contraction. Hiring from that shock stays inside a band around the usual employment target, so unemployment may move less than the size suggests. A productivity shock multiplies capacity by one plus this share while it expands, and it slows price growth. A credit shock widens lending during the expansion, writes off 10 percent of firm loans at the turning point, and tightens lending during the contraction.',
  ),
  numberSlider(
    'tax.incomeRate',
    'Income tax rate',
    'publicFinance',
    'share',
    0.2,
    0,
    0.5,
    'Share of household and AI-agent income paid to the treasury each month. Each payer pays from its deposit, up to the balance it has. Revenue lands in the government deposit and is the first source of funds for the household UBI grant and for government purchases. The default matches the spending share so the treasury starts near balance when the grant is off. If taxes do not cover the grant or purchases, the treasury issues bonds and the first bank holds them. Changing the tax rate does not by itself change how much the government buys.',
  ),
  numberSlider(
    'government.spendingShareOfGDP',
    'Government spending share',
    'publicFinance',
    'share of GDP',
    0.2,
    0,
    0.5,
    'Share of household smoothed income that the government buys from firms. It shops first at the firms holding the most inventory. Households spend what remains: their spending share of income starts at one minus this value, then tilts with how impatient they are relative to the mean. Raising this share shifts purchases from households to the government. If tax revenue does not cover the bill, the treasury issues bonds. It is a closed-economy purchase share, set so the goods market can clear, not an estimate for a particular country.',
  ),
  numberSlider(
    'government.ubiShare',
    'UBI share of AI GDP',
    'publicFinance',
    'share',
    0.25,
    0,
    1,
    'Fraction of the AI slice of monthly nominal GDP paid equally to every household. The AI slice is the AI share of output times price times real GDP. The grant starts at zero when no AI capacity is adopted and rises with that share, so it phases in along the adoption curve rather than as a fixed stipend. At 0.25 with an AI share of 0.36, about 9 percent of that month’s nominal GDP is paid out. Tax, including tax on AI agents, is collected first. If the treasury cannot cover the grant, it issues bonds to the first bank. Households only receive the grant. Agents do not. At 0 the grant is off even while AI is adopted.',
  ),
  numberSlider(
    'government.treasuryBufferMonths',
    'Treasury buffer',
    'publicFinance',
    'months',
    1,
    0,
    24,
    'Months of this tick’s outlays the treasury keeps. Outlays are the household grant, goods the treasury actually bought, and bond coupons. Cash above that is paid to households in proportion to that tick’s income, after tax, and counted in their income, so it raises next month’s demand and is not taxed in the collection that funded it. The share follows income so the refund does not flatten the distribution. At 1 the treasury cannot build a stock of deposits. At 0 any surplus is rebated the same month. A shortfall still issues bonds.',
  ),
  numberSlider(
    'centralBank.inflationTarget',
    'Inflation target',
    'centralBank',
    '1/year',
    0.02,
    0,
    0.06,
    'Annual CPI inflation the fiat central bank aims for. Fiat prices and wages trend at this rate. When inflation is above the target the policy rate rises, and when inflation is below it the policy rate falls. The default of 0.02 is the 2 percent goal stated by many inflation-targeting central banks. Bitcoin and hybrid regimes do not follow this target. Their price trend is minus baseline productivity growth.',
  ),
  numberSlider(
    'centralBank.inflationWeight',
    'Inflation weight',
    'centralBank',
    'coefficient',
    1.5,
    1,
    3,
    'How hard the fiat policy rate reacts when inflation misses the target. The rule adds this weight times (inflation minus the target), on top of an inflation term that already enters one-for-one. At 1.5, inflation one percentage point above target adds 1.5 points to the policy rate from this term alone. The weight is used only in the fiat regime. The policy rate cannot fall below zero.',
  ),
  numberSlider(
    'centralBank.outputWeight',
    'Output weight',
    'centralBank',
    'coefficient',
    0.5,
    0,
    1.5,
    'How hard the fiat policy rate reacts when unemployment is away from the natural rate. The natural rate starts at 6 percent and rises as AI raises capacity. The rule adds this weight times (natural unemployment minus the unemployment rate) times the human share of output. A slack labor market cuts the rate and a tight one raises it. At 0.5 with no AI, unemployment one point below the natural rate adds half a point to the policy rate. Late in adoption the same point gap moves the rate less. Bitcoin and hybrid regimes do not use this weight. The policy rate cannot fall below zero.',
  ),
  numberSlider(
    'centralBank.rateSmoothing',
    'Policy-rate smoothing',
    'centralBank',
    'weight',
    0.5,
    0,
    0.95,
    'Weight on last month’s policy rate when publishing this month’s rate. The rest is the new Taylor setting under fiat, or the new market loan rate under bitcoin and hybrid. A high weight stops one capped price move from swinging the opening rate between 0 and the mid-teens. At 0 the published rate is the raw setting. The weight cannot be 1, so a sustained inflation gap still moves the rate.',
  ),
  numberSlider(
    'bank.reserveRequirement',
    'Reserve requirement',
    'centralBank',
    'share',
    0.1,
    0,
    0.3,
    'Share of deposits that must be backed by central-bank reserves. In the fiat regime, if reserves are short of this share, the central bank creates the gap and credits it to the first bank. That is how fiat base money expands when the requirement binds. Bitcoin and hybrid regimes do not create reserves to meet this number, so the same setting does not expand their base money.',
  ),
  numberSlider(
    'bank.capitalRatio',
    'Bank capital ratio',
    'credit',
    'share',
    0.08,
    0.04,
    0.2,
    'Minimum bank equity relative to loans. Lending room is equity divided by this ratio, minus loans already outstanding. A higher ratio leaves less room to lend from the same equity and a thicker cushion when loans are written off. A lower ratio does the opposite. Banks start with extra equity so they have room to lend. Equity at or below zero is recorded as a bank failure. The default is near the Basel III common-equity floor, applied here to every loan rather than to risk-weighted assets.',
  ),
  enumSlider(
    'bank.resolution',
    'Bank resolution',
    'credit',
    'mode',
    'off',
    ['off', 'merge'],
    'What happens when bank equity falls to zero or below. Off only marks the bank failed so it stops lending (previous behavior). Merge transfers deposits and loans to a surviving bank by id, or bails in depositors at a sole bank, including the treasury deposit at bank 0, until equity meets the capital target. A bank already at that target is not bailed in again. Hybrid lender-of-last-resort injection still runs first; if equity is still negative, hybrid uses the same resolution. The monetary preset uses merge.',
  ),
  numberSlider(
    'bank.depositHaircut',
    'Deposit haircut on resolution',
    'credit',
    'share',
    0,
    0,
    0.2,
    'Share of deposits written off when a failed bank is merged or bailed in. The write-down raises bank equity. At 0, merge transfers balances in full and a sole-bank bail-in writes down only as much as needed to restore the capital target. Unused when bank resolution is off.',
  ),
  numberSlider(
    'credit.endogenousWeight',
    'Endogenous credit weight',
    'credit',
    'share',
    0,
    0,
    1,
    'How strongly lending expands in calm periods and contracts when leverage or defaults rise. At 0, credit moves only with the credit shock and with ordinary firm borrowing. Above 0, calm lending room is wider by one plus four times this weight. From the first anniversary, calm banks lend this weight times 12 percent of household deposits, split across firms and still inside that room. Stress builds when loans exceed credit.leverageStart times household deposits or when loans are written off. Above a small stress limit, new endogenous borrowing stops, lending room shrinks, and firms repay. At 0 the previous credit path is unchanged.',
  ),
  numberSlider(
    'credit.leverageStart',
    'Credit leverage start',
    'credit',
    'share',
    0.02,
    0.02,
    1.5,
    'Loan-to-deposit ratio above which endogenous credit stress begins to build. At the default of 0.02, calm lending stops once loans exceed 2 percent of household deposits. Raise it toward 1 so calm banks can hold a loan book on the order of deposits before stress cuts lending. Unused when endogenous credit weight is 0.',
  ),
  numberSlider(
    'credit.householdMortgageShare',
    'Household mortgage credit share',
    'credit',
    'share',
    0,
    0,
    1,
    'Share of each bank’s capital capacity reserved for household mortgages and consumer loans. At 0, households compete with firms for the same lending room, which often leaves no room for new mortgages after the opening book. Above 0, that share of equity over the capital ratio is kept for household credit, and firm lending uses the remainder. The monetary preset uses 0.25.',
  ),
  numberSlider(
    'credit.rateTransmission',
    'Policy-rate transmission',
    'credit',
    'share',
    0,
    0,
    1,
    'How strongly the real policy rate cuts new consumer borrowing and firm capital installation. The factor is max(0, 1 − weight × max(0, policy rate − inflation)). At 0 the previous credit and investment path is unchanged.',
  ),
  numberSlider(
    'productivity.endogenousWeight',
    'Endogenous productivity weight',
    'background',
    'share',
    0,
    0,
    1,
    'Share of productivity growth that tracks capacity utilization (real GDP over a reference staffing path) instead of only the baseline rate. At 0 growth follows productivity.baseGrowth alone.',
  ),
  enumSlider(
    'population.bequests',
    'Bequest rule',
    'background',
    'mode',
    'firstHousehold',
    ['firstHousehold', 'skillWeighted'],
    'Who receives a household’s deposit when population growth removes that household. firstHousehold keeps the previous transfer to household 0. skillWeighted gives the estate to the remaining households in proportion to skill to the 16th, so it concentrates on the highest-skill heirs instead of spreading the estate evenly.',
  ),
  numberSlider(
    'bitcoin.marketPriceWeight',
    'Bitcoin market price weight',
    'regime',
    'share',
    0,
    0,
    1,
    'How far the recorded bitcoin exchange rate can move with issuance and trust separately from the goods CPI in satoshis. At 0 the bitcoin price series stays on the previous path. Above 0 it also responds to that month’s issuance relative to coins outstanding and to money.bitcoinTrust.',
  ),
  numberSlider(
    'household.durableShare',
    'Durable spending share',
    'behavior',
    'share',
    0,
    0,
    0.5,
    'Share of discretionary goods spending treated as durable purchases that can be delayed when the real return on money is high. At 0 all goods spending is nondurable as before.',
  ),
  numberSlider(
    'transition.gradualWeight',
    'Gradual transition weight',
    'regime',
    'share',
    0,
    0,
    1,
    'When a transition window is positive and this weight is positive, each month converts one over the months still left, times this weight, of every deposit and of firm and household debt into bitcoin units at the current bitcoin price. Goods can be paid from either balance. The debt haircut writes off that share of the slice converted that month. At 1 the stock converts in equal monthly slices and both balances are in use through the window. At 0 the one-step rebase at the end of the window is unchanged.',
  ),
  numberSlider(
    'bank.depositPassThrough',
    'Deposit rate pass-through',
    'credit',
    'share',
    0,
    0,
    1,
    'Share of the policy rate paid on household deposits. The deposit rate is this fraction times the policy rate. It enters the real return on money that can cut discretionary spending. Banks pay that monthly interest from this tick’s loan interest and, under fiat, from interest on reserves. They do not spend the capital buffer. At 0 deposits pay nothing. It cannot cut the food and housing spending floor.',
  ),
  numberSlider(
    'bank.depositInterestSubsidy',
    'Deposit interest subsidy',
    'credit',
    'share',
    0,
    0,
    1,
    'Share of any household deposit-interest shortfall the fiat central bank covers after loan interest and interest on reserves. The subsidy adds reserves and equity and lowers private equity so the vault identity holds, then interest is paid to depositors. It does not spend the capital buffer. At 0 there is no subsidy. Bitcoin and hybrid ignore this slider.',
  ),
  numberSlider(
    'centralBank.bondPurchaseShare',
    'Central-bank bond purchase share',
    'centralBank',
    'share',
    0,
    0,
    1,
    'Share of new government bonds bought by creating central-bank reserves in the fiat regime. The rest stay on commercial-bank balance sheets. Bitcoin and hybrid ignore this slider; their base money does not rise with bond finance. At 0 every shortfall is held by the first bank with no new reserves from this channel.',
  ),
  numberSlider(
    'centralBank.moneyGrowth',
    'Fiat money growth',
    'centralBank',
    'share',
    1,
    0,
    1,
    'How strongly the fiat central bank grows broad money with the inflation target and productivity. Each month deposits and reserves change by this weight times (inflation target + baseline productivity + inflation gap) / 12 times deposits. A contraction draws reserves from banks in id order, starting with the first, and stops when those reserves are used up. At 1 on the 2 percent target with 1 percent productivity growth, deposits grow about 3 percent a year when inflation is on target. Below-target inflation raises growth; above-target slows it. Bitcoin and hybrid ignore this slider. At 0 the fiat stock stays fixed.',
  ),
  enumSlider(
    'centralBank.injectionChannel',
    'Money injection channel',
    'centralBank',
    'channel',
    'proRataDeposits',
    ['proRataDeposits', 'governmentSpending', 'newLoans', 'assetPurchase'],
    'Where new fiat money first lands when money growth is positive. proRataDeposits splits new deposits and reserves by existing household balances. governmentSpending credits the treasury, adds reserves, and buys goods from firms in the same tick. newLoans books firm loans and firm deposits and does not create reserves; those loans are repaid before the cash is paid out as wages. assetPurchase credits firm deposits and a bond claim, and does not book a loan. A contraction withdraws from the sector that channel credits, and only up to the balances that exist. Bitcoin and hybrid ignore this slider.',
  ),
  numberSlider(
    'centralBank.spendNewMoney',
    'Spend new money',
    'centralBank',
    'share',
    0,
    0,
    1,
    'Share of new fiat blended into household smoothed income when prices.trendWeight is below 1. On the household channel, 0 still blends a thin opening (deposits below 24 months). On the loan, bond, and treasury channels, only this share is blended, so those receipts are not a silent hoard. Bitcoin and hybrid ignore this slider.',
  ),
  numberSlider(
    'government.stabilizer',
    'Fiscal stabilizer',
    'publicFinance',
    'coefficient',
    0,
    0,
    2,
    'How much government goods spending responds to unemployment. Under fiat, the spending share rises by this coefficient times the gap of unemployment above the natural rate, capped at 0.8. Under bitcoin or hybrid, spending cannot exceed tax deposits plus bonds banks can hold from unused savings, so the stabilizer cannot expand base money. At 0 the spending share stays at the government spending slider.',
  ),
  numberSlider(
    'government.bondRate',
    'Government bond rate',
    'publicFinance',
    '1/year',
    0,
    0,
    0.12,
    'Annual coupon on government bonds held by banks. Each month the treasury pays one twelfth of this rate times bonds outstanding. The payment leaves the treasury deposit and raises bank equity. If the treasury cannot cover it, the shortfall is financed like any other deficit. At 0 bonds pay no coupon and the previous fiscal path is unchanged.',
  ),
  numberSlider(
    'transition.lengthMonths',
    'Transition length',
    'regime',
    'months',
    0,
    0,
    120,
    'Months of a one-time fiat-to-bitcoin change. At 0 there is no transition and regime.type selects a steady rule set. A positive length starts the run on fiat rules with satoshi balances. When gradual weight is 0, the last month may haircut debts, reassign deposits by holder concentration, clear government bonds on bank books, and switch the active regime to bitcoin. When gradual weight is positive, deposits and debts convert into bitcoin over the window and the regime flips at the end. Monetization stays off afterward.',
  ),
  numberSlider(
    'transition.debtHaircut',
    'Transition debt haircut',
    'regime',
    'share',
    0,
    0,
    0.5,
    'Share of the firm loans, mortgages, and consumer loans converted in a transition month that is written off. At 0 that slice converts one-for-one into bitcoin debt. When gradual weight is 0 the whole stock is converted on the last month. Unused when the transition length is 0.',
  ),
  numberSlider(
    'transition.holderConcentration',
    'Transition holder concentration',
    'regime',
    'share',
    0.5,
    0,
    0.99,
    'How concentrated the post-conversion deposit distribution is. Household deposits are reassigned with weights of skill raised to one plus four times this value. At 0 the weights are skill itself. At 0.99 high-skill households receive almost all deposits. Unused when the transition length is 0.',
  ),
  enumSlider(
    'regime.type',
    'Monetary regime',
    'regime',
    'regime',
    'fiat',
    ['fiat', 'bitcoin', 'hybrid'],
    'Rule set for base money, interest, and government finance. Fiat prices trend toward the inflation target, the central bank sets the policy rate from inflation and unemployment, and it creates reserves when the reserve requirement binds. Money is integer cents. Bitcoin does not grow the money stock with the economy, so the price trend is minus productivity growth. New loans cannot exceed unused savings, and a government budget shortfall is financed by bonds rather than new central-bank money. Money is satoshis, including fractions of a satoshi. Hybrid uses that same unit and price trend, and it does not target inflation. If a bank equity balance goes negative, the hybrid central bank injects enough reserves and vault cash to make that equity positive. That injection is the only base-money growth in the hybrid regime.',
  ),
  enumSlider(
    'bitcoin.lendingModel',
    'Bitcoin lending model',
    'credit',
    'model',
    'maturityMatched',
    ['maturityMatched', 'fullReserve'],
    'How much of household deposits can fund loans when the regime is bitcoin or hybrid. Maturity matched treats 25 percent of household deposits as lendable savings. Full reserve treats 10 percent as lendable savings. New credit in those regimes cannot exceed savings minus loans already outstanding, and the loan rate moves toward the gap between loans and that savings stock. In the fiat regime the central bank sets the policy rate and lending room follows bank capital, so this choice does not change the fiat interest-rate rule.',
  ),
];
