import type { Slider } from '../builders.js';
import { enumSlider, numberSlider } from '../builders.js';

export const MARKET_SLIDERS: readonly Slider[] = [
  numberSlider(
    'labor.maxApplications',
    'Job applications',
    'behavior',
    'applications per tick',
    3,
    1,
    8,
    'How many firms an unemployed household can ask for work in one month. The run rounds this to a whole number. Hiring fills openings until employment is near 94 percent of households times the human share of output, with a small tilt when a demand shock is on. That target rises the natural unemployment rate as AI capacity grows. A searcher walks a short list of firms and takes the first one that still has room. A household displaced by automation is limited to one application even when this slider is higher. More applications make it easier to find a firm that is still hiring. This slider only limits how wide the search is.',
  ),
  numberSlider(
    'labor.wageElasticity',
    'Wage elasticity of hiring',
    'behavior',
    'coefficient',
    0.5,
    0,
    3,
    'How strongly the hiring quota responds when the real wage is away from its cost reference. The quota starts at 94 percent of households times the human share of output. The reference is 1 / (1 + firm markup) times economy-wide productivity. It omits labor-market tightness and the productivity impulse. The quota is multiplied by clamp(1 − this elasticity × (real wage / reference − 1), 0.5, 1.25). A posted wage above the reference cuts hiring; a wage below it raises hiring. The default of 0.5 cuts the quota by 5 percent when the real wage is 10 percent above the reference. At 0 the quota ignores the real wage. When the scaled quota is below current employment, firms separate workers down to the quota.',
  ),
  enumSlider(
    'labor.firmLevelHiring',
    'Firm-level hiring',
    'behavior',
    'switch',
    'on',
    ['off', 'on'],
    'Who sets the hiring target. On, each firm wants the headcount whose capacity matches its smoothed sales (plus unmet goods demand outside a demand contraction, floored at 75 percent of capacity), vacancies go to understaffed firms, and the aggregate sits between the cost quota times one minus the monthly shed share and the cost quota. When that floor is above the sum of firm targets, remaining vacancies fill on the ordinary path. Firms shed at most 5 percent of employed workers in a month when the target falls. Off keeps the economy-wide quota: 94 percent of households times the human share of output, tilted by demand and by the wage elasticity.',
  ),
  numberSlider(
    'production.alpha',
    'Capital elasticity',
    'behavior',
    'share',
    0.33,
    0.2,
    0.5,
    'Exponent on capital in the Cobb–Douglas production function. Capacity is productivity times capital raised to this power times labor raised to one minus this power. A higher value means output responds more to capital and less to employment. Capital starts equal to employment at that firm and depreciates at 0.5 percent a month. The default near one third matches the usual capital share of income.',
  ),
  numberSlider(
    'production.demandWeight',
    'Demand weight on output',
    'behavior',
    'share',
    0.5,
    0,
    1,
    'How far monthly output follows recent sales instead of full capacity. At 0 every firm produces its capacity, and unsold goods pile into inventory. Above 0, desired output is smoothed sales plus the gap to one month of inventory, capped at capacity, and output is a mix of that quantity and full capacity. The default of 0.5 mixes capacity and demand so a calm opening mortgage book does not collapse employment. At 1, output equals desired sales. A demand shortfall then lowers real GDP in later months.',
  ),
  numberSlider(
    'goods.sampleSize',
    'Shops sampled',
    'behavior',
    'firms',
    4,
    1,
    12,
    'How many firms a household can visit while spending its monthly budget. Desired spendable budgets are first scaled by min(1, stock value / desired) so scarce inventory is shared in proportion to what households want to spend. The walk then starts at a random firm and continues to the following firms until the scaled budget is spent, the visits run out, or those firms are out of stock. Residual unmet demand lifts prices when capacity demand is not soft. A larger sample makes a leftover stockout easier to work around. Shoppers do not sort firms by price.',
  ),
];
