import type { Slider } from '../builders.js';
import { numberSlider } from '../builders.js';

export const MONEY_SLIDERS: readonly Slider[] = [
  numberSlider(
    'money.choiceSpeed',
    'Money choice speed',
    'regime',
    'share per tick',
    0,
    0,
    1,
    'How fast currency shares move toward the monies people prefer. Bitcoin starts at its current weight in global assets, about 0.4 percent. Stablecoins and CBDC start from their opening sliders, and fiat is the rest. Each month the shares step toward the mix implied by legal tender, trust, payment friction, and the real return. Bitcoin issuance follows the halving schedule and is not a slider. At 0 the shares stay at that opening mix. Above 0 the shares and exchange rates move; the regime control still selects the policy-rate rule, fiat money growth, reserve accommodation, and the hybrid lender of last resort. The default of 0 keeps currency adoption off so regime comparisons are not blended.',
  ),
  numberSlider(
    'money.stablecoinStart',
    'Opening stablecoin share',
    'regime',
    'share',
    0.01,
    0,
    1,
    'Share of money balances that start as stablecoins. Stablecoin trust and friction are fixed in the model. The default of 0.01 is a small opening stake. At 0 none of the opening mix is a stablecoin.',
  ),
  numberSlider(
    'money.cbdcStart',
    'Opening CBDC share',
    'regime',
    'share',
    0.005,
    0,
    1,
    'Share of money balances that start as a central-bank digital currency. The default of 0.005 is a small opening stake. At 0 none of the opening mix is CBDC.',
  ),
  numberSlider(
    'money.fiatLegalTender',
    'Fiat legal-tender pull',
    'regime',
    'score',
    1.5,
    0,
    2,
    'How strongly fiat is pulled into use by taxes, courts, and legal tender. It is the fiat score in the money-choice softmax. The default of 1.5 keeps fiat the largest money when choice is on. Unused when money choice speed is 0.',
  ),
  numberSlider(
    'money.bitcoinTrust',
    'Bitcoin trust',
    'regime',
    'score',
    0.4,
    0,
    2,
    'How willing holders are to keep bitcoin. The bitcoin score is this trust plus the real return, minus a small payment friction. The default of 0.4 is a modest stake beside fiat legal tender. Unused when money choice speed is 0.',
  ),
];
