import type { Slider } from '../builders.js';
import { numberSlider } from '../builders.js';

export const WELFARE_SLIDERS: readonly Slider[] = [
  numberSlider(
    'welfare.housingSecurityWeight',
    'Housing security weight',
    'welfare',
    'coefficient',
    0.5,
    0,
    2,
    'How much housing security adds to human well-being. Well-being is the log of real consumption, floored at 0.01, plus this weight times housing security. Security is real income relative to the median, divided by one plus the housing price relative to the CPI, and kept between 0 and 1. A higher weight makes income gaps and housing prices matter more on the well-being chart. It does not change what anyone earns, buys, or borrows. AI agents are left out of well-being.',
  ),
  numberSlider(
    'welfare.weightInequality',
    'Inequality weight',
    'welfare',
    'weight',
    0,
    0,
    1,
    'Weight on equality in the optional composite index shown in the assumption ledger. The term is this weight times (1 minus the wealth Gini) at the last tick, so a lower Gini scores higher. The index is computed in the page after the run. Moving the weight does not change prices, jobs, or wealth inside the simulation. The index stays off while every composite weight is zero. The four weights are not on a common scale: a wealth or well-being level can dwarf a Gini term.',
  ),
  numberSlider(
    'welfare.weightMedianWealth',
    'Median wealth weight',
    'welfare',
    'weight',
    0,
    0,
    1,
    'Weight on median real wealth in the optional composite index. The term is this weight times median real wealth at the last tick. That level is a large number next to a Gini or an unemployment rate, so a small weight can dominate the index. The index is computed in the page after the run and does not change wealth inside the simulation. The index stays off while every composite weight is zero.',
  ),
  numberSlider(
    'welfare.weightWellbeing',
    'Well-being weight',
    'welfare',
    'weight',
    0,
    0,
    1,
    'Weight on mean human well-being in the optional composite index. The term is this weight times mean well-being at the last tick. Well-being itself already includes consumption and housing security. This weight only changes how that result is scored in the index, which the page computes after the run. The index stays off while every composite weight is zero.',
  ),
  numberSlider(
    'welfare.weightStability',
    'Stability weight',
    'welfare',
    'weight',
    0,
    0,
    1,
    'Weight on labor-market stability in the optional composite index. The term is this weight times a score of slack relative to the natural unemployment rate, shifted so a 6 percent natural rate still scores as one minus unemployment. As AI raises the natural rate, resting at that rate scores like full employment rather than a collapse. The index is computed in the page after the run. The weight does not change hiring. The index stays off while every composite weight is zero.',
  ),
];
