/**
 * Registry defaults before the 2026-trajectory retarget. Phase tests that check
 * "matches the prior path when the new slider is off" need this world so one
 * mechanism can be toggled without the other new defaults moving the path.
 */
export const FEATURE_OFF: Readonly<Record<string, number | string>> = {
  'money.choiceSpeed': 0,
  'money.stablecoinStart': 0,
  'money.cbdcStart': 0,
  'money.fiatLegalTender': 1,
  'money.bitcoinTrust': 0.3,
  'bitcoin.marketPriceWeight': 0,
  'centralBank.stimulus': 1,
  'centralBank.stimulusLag': 6,
  'centralBank.zombieSupport': 0,
  'centralBank.outputWeight': 0.5,
  'centralBank.bondPurchaseShare': 0,
  'centralBank.spendNewMoney': 0,
  'government.stabilizer': 0,
  'government.bondRate': 0,
  'bank.depositInterestSubsidy': 0,
  'bank.depositPassThrough': 0,
  'bank.capitalRatio': 0.08,
  'bank.resolution': 'off',
  'credit.endogenousWeight': 0,
  'credit.leverageStart': 0.02,
  'credit.householdMortgageShare': 0,
  'credit.rateTransmission': 0,
  'housing.tenureChoice': 'off',
  'housing.marketClearing': 'off',
  'housing.monetaryPremium': 0,
  'goods.housingSupplyGrowth': 0,
  'production.demandWeight': 0,
  'labor.firmLevelHiring': 'off',
  'firm.investmentHurdle': 'off',
  'productivity.endogenousWeight': 0,
  'household.realReturnSensitivity': 0,
  'household.durableShare': 0,
  'expectations.anchorWeight': 0,
  'household.openingDepositMonths': 36,
  'household.skillSigma': 0.5,
  'population.growth': 0,
  'population.bequests': 'firstHousehold',
  'ai.bullishness': 0,
  'ai.adoptionMidpointYear': 10,
  'ai.roboticsStartYear': 20,
  'ai.roboticsRampYears': 16,
  'ai.computeProductivity': 0,
  'agent.marketDepth': 0,
  'prices.trendWeight': 1,
};
